export const BANKS = [
  { key: "BCA", value: "Bank Central Asia" },
  { key: "MANDIRI", value: "Bank Mandiri" },
  { key: "BNI", value: "Bank Negara Indonesia" },
  { key: "BRI", value: "Bank Rakyat Indonesia" },
  { key: "BTN", value: "Bank Tabungan Negara" },
  { key: "CIMB", value: "CIMB Niaga" },
  { key: "PERMATA", value: "Bank Permata" },
  { key: "DANAMON", value: "Bank Danamon" },
  { key: "MAYBANK", value: "Maybank Indonesia" },
  { key: "OCBC", value: "OCBC NISP" },
  { key: "PANIN", value: "Bank Panin" },
  { key: "BTPN", value: "Bank BTPN" },
  { key: "MEGA", value: "Bank Mega" },
  { key: "SINARMAS", value: "Bank Sinarmas" },
  { key: "MESTIKA", value: "Bank Mestika Dharma" },
  { key: "WOORI", value: "Bank Woori Saudara" },
  { key: "JTRUST", value: "Bank JTrust Indonesia" },
  { key: "KEBHANA", value: "KEB Hana Bank" },
  { key: "COMMONWEALTH", value: "Commonwealth Bank" },
  { key: "UOB", value: "UOB Indonesia" },
  { key: "HSBC", value: "HSBC Indonesia" },
  { key: "CTBC", value: "CTBC Indonesia" },
  { key: "BJB", value: "Bank BJB" },
  { key: "DKI", value: "Bank DKI" },
  { key: "JATENG", value: "Bank Jateng" },
  { key: "JATIM", value: "Bank Jatim" },
  { key: "BPD DIY", value: "Bank BPD DIY" },
  { key: "SUMUT", value: "Bank Sumut" },
  { key: "NAGARI", value: "Bank Nagari" },
  { key: "RIAUKEPRI", value: "Bank Riau Kepri" },
  { key: "SUMSEL", value: "Bank Sumsel Babel" },
  { key: "LAMPUNG", value: "Bank Lampung" },
  { key: "KALSEL", value: "Bank Kalsel" },
  { key: "KALTENG", value: "Bank Kalteng" },
  { key: "KALTIMTARA", value: "Bank Kaltimtara" },
  { key: "SULSELBAR", value: "Bank Sulselbar" },
  { key: "SULTRA", value: "Bank Sultra" },
  { key: "SULUTGO", value: "Bank SulutGo" },
  { key: "NTB", value: "Bank NTB Syariah" },
  { key: "NTT", value: "Bank NTT" },
  { key: "MALUKU", value: "Bank Maluku Malut" },
  { key: "PAPUA", value: "Bank Papua" },
  { key: "ACEH", value: "Bank Aceh Syariah" },
  { key: "GOPAY", value: "gopay" },
  { key: "OVO", value: "ovo" },
  { key: "DANA", value: "dana" },
  { key: "SHOPEEPAY", value: "shopeepay" },
];
