export const MENU_PERMISSION = {
    TODAY_TASK: [
        "CEO",
        "CMO",
        "COO",
        "GM",
        "Manager",
        "HRD",
        "Manager Produksi",
        "Spv Cutting",
        "Spv Produksi",
        "Spv Finishing",
        "Spv Gudang",
        "Tukang Potong",
        "Mandor",
    ],
    PRODUCTION_TASK: [
        "CEO",
        "CMO",
        "COO",
        "GM",
        "Manager",
        "HRD",
        "Manager Produksi",
        "Penjahit",
        "Finishing",
        "Mandor",
        "Spv Cutting",
        "Spv Produksi",
        "Spv Finishing",
        "Spv Gudang",
        "Staff Produksi",
        "Packing",
        "Staff Admin",
    ],
    SET_SEWN: [
        "CEO",
        "CMO",
        "COO",
        "GM",
        "Manager",
        "HRD",
        "Manager Produksi",
        "Mandor",
        "Spv Produksi",
        "Spv Gudang",
        "Staff Gudang",
    ],
    PRODUCTION_PLAN: [
        "CEO",
        "CMO",
        "COO",
        "GM",
        "Manager",
        "HRD",
        "Manager Produksi",
        "Mandor",
        "Spv Cutting",
        "Spv Produksi",
        "Spv Finishing",
        "Spv Gudang",
    ],
    PRODUCTION_MONITORING: [
        "CEO",
        "CMO",
        "COO",
        "GM",
        "Manager",
        "HRD",
        "Manager Produksi",
        "Spv Cutting",
        "Spv Produksi",
        "Spv Finishing",
        "Spv Gudang",
    ],
    MATERIAL_REQUEST: [
        "CEO",
        "CMO",
        "COO",
        "GM",
        "Manager",
        "HRD",
        "Manager Produksi",
        "Spv Cutting",
        "Spv Produksi",
        "Spv Finishing",
        "Spv Gudang",
        "Mandor",
    ],
    PRODUCT_PRIORITY_LIST: [
        "CEO",
        "CMO",
        "COO",
        "GM",
        "Manager",
        "HRD",
        "Manager Produksi",
        "Spv Cutting",
        "Spv Produksi",
        "Spv Finishing",
        "Spv Gudang",
        "Mandor",
        "Finishing",
    ],
    PRODUCT_PRIORITY_ADD: [
        "CEO",
        "CMO",
        "COO",
        "GM",
        "Manager",
        "HRD",
        "Manager Produksi",
        "Spv Cutting",
        "Spv Produksi",
        "Spv Finishing",
        "Spv Gudang",
        "Mandor",
    ],
    PRODUCT_PLAN: [
        "CEO",
        "CMO",
        "COO",
        "GM",
        "Manager",
        "HRD",
        "Manager Produksi",
        "Spv Cutting",
        "Spv Produksi",
        "Spv Finishing",
        "Spv Gudang",
        "Mandor",
        "Foto Produk",
    ],
    PRODUCT_ADD: [
        "CEO",
        "CMO",
        "COO",
        "GM",
        "Manager",
        "HRD",
        "Manager Produksi",
        "Spv Cutting",
        "Spv Produksi",
        "Spv Finishing",
        "Spv Gudang",
        "Mandor",
        "Foto Produk",
    ],
    LIST_STOCK: [
        "CEO",
        "CMO",
        "COO",
        "GM",
        "Manager",
        "HRD",
        "Manager Produksi",
        "Spv Cutting",
        "Spv Produksi",
        "Spv Finishing",
        "Spv Gudang",
        "Mandor",
    ],
    ADD_STOCK: [
        "CEO",
        "CMO",
        "COO",
        "GM",
        "Manager",
        "HRD",
        "Manager Produksi",
        "Spv Cutting",
        "Spv Produksi",
        "Spv Finishing",
        "Spv Gudang",
        "Mandor",
    ],
    CALCULATE_STOCK: [
        "CEO",
        "CMO",
        "COO",
        "GM",
        "Manager",
        "HRD",
        "Manager Produksi",
        "Spv Cutting",
        "Spv Produksi",
        "Spv Finishing",
        "Spv Gudang",
        "Mandor",
    ],
    ADD_MATERIAL: [
        "CEO",
        "CMO",
        "COO",
        "GM",
        "Manager",
        "HRD",
        "Manager Produksi",
        "Spv Cutting",
        "Spv Produksi",
        "Spv Finishing",
        "Spv Gudang",
        "Mandor",
    ],
    ACCESSORIES: [
        "CEO",
        "CMO",
        "COO",
        "GM",
        "Manager",
        "HRD",
        "Manager Produksi",
        "Spv Cutting",
        "Spv Produksi",
        "Spv Finishing",
        "Spv Gudang",
        "Mandor",
        "Live",
        "Finishing",
        "Tukang Potong",
        "Penjahit",
    ],
    PRODUCT: [
        "CEO",
        "CMO",
        "COO",
        "GM",
        "Manager",
        "HRD",
        "Manager Produksi",
        "Spv Cutting",
        "Spv Produksi",
        "Spv Finishing",
        "Spv Gudang",
        "Mandor",
        "Foto Produk",
        "Live",
        "Finishing",
        "Tukang Potong",
        "Penjahit",
    ],
    CASHIER: [
        "CEO",
        "CMO",
        "COO",
        "GM",
        "Manager",
        "Toko",
        "T O K O",
        "Finance",
    ],
    BUYER_DATA: [
        "CEO",
        "CMO",
        "COO",
        "GM",
        "Manager",
        "Toko",
        "T O K O",
        "Finance",
    ],
    SELLING_REPORT: [
        "CEO",
        "CMO",
        "COO",
        "GM",
        "Manager",
        "Toko",
        "T O K O",
        "Finance",
    ],
    APPROVAL: ["CEO", "CMO", "COO", "GM", "Manager", "HRD", "Manager Produksi"],
    ABSENCE_CORRECTION: [
        "CEO",
        "CMO",
        "COO",
        "GM",
        "Manager",
        "HRD",
        "Manager Produksi",
    ],
    SHOW_SCAN_BATCH: [
        "CEO",
        "CMO",
        "COO",
        "GM",
        "Manager",
        "Finishing",
        "Mandor",
        "Spv Cutting",
        "Spv Produksi",
        "Spv Finishing",
        "Spv Gudang",
        "Staff Produksi",
        "Packing",
        "Staff Admin",
    ],
    CAN_MUTE: ["CEO", "CMO", "COO", "GM", "Manager"],
};
